#!/usr/bin/env bash
:
shopt -s nocasematch
shopt -s nullglob
shopt -s extglob

unset IMG

[[ ! -f ${PWD}/.karpos-root ]] && printf "Anchor not found!\n"


[[ ${#1} -eq 0 ]] && printf 'no file specified\n' && exit 1

dirparent="$(basename "$(pwd)")"
filename="${@:-1}"
curdir="$(dirname "$(pwd)")"


# required directories
[[ ! -d $PWD/aux ]] && mkdir aux
[[ ! -d $PWD/pdf ]] && mkdir pdf


# optional directories
[[ -d $PWD/figures ]] && IMG=TRUE



# function tree {
#     find .. -name '*' | sed -e 's/^/|-/' -e 's/[^-][^\/]*\//|   /g' -e 's/|   \([A-Za-z0-9_.]\)/|   +--\1/'
# }



